
/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.47
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

// =====================================================================#
//                                                                      #
//   A replacement class for WPIcon, which makes it possible to change  #
//   the icon of one or more objects, by dropping them on an icon       #
//   object.                                                            #
//   Copyright (C) 1999 Jens Borch Christiansen                         #
//                                                                      #
//   This program is free software; you can redistribute it and/or      #
//   modify it under the terms of the GNU General Public License as     #
//   published by the Free Software Foundation; either version 2 of     #
//   the License, or (at your option) any later version.                #
//                                                                      #
//   This program is distributed in the hope that it will be useful,    #
//   but WITHOUT ANY WARRANTY; without even the implied warranty of     #
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      #
//   GNU General Public License for more details.                       #
//                                                                      #
//   You should have received a copy of the GNU General Public License  #
//   along with this program; if not, write to the Free Software        #
//   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA           #
//   02111-1307  USA                                                    #
//                                                                      #
// =====================================================================#

#ifndef SOM_Module_ddicon_Source
#define SOM_Module_ddicon_Source
#endif
#define DDIcon_Class_Source
#define M_DDIcon_Class_Source

#include "DDIcon.ih"

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <wpclsmgr.h>
#include <wpobject.h>
#include <wpshadow.h>
#include <wpfolder.h>
#include <Helpers/winh.h> // Xfolder helper header used for adding items to the popup menus
#include "DDIconIDS.h"    // Menu and dialog id's


/*
 * If  _PMPRINTF_ is defined then debug using pmprintf
 */
//#define _PMPRINTF_
#include <PMPRINTF.H>

/*
 * If an object is an shadow then return the original object
 */
WPObject* GetOriginalObject(WPObject* pObject)
{
   if(_somIsA(pObject, _WPShadow))
   {
      return _wpQueryShadowedObject(pObject, FALSE);
   }
   else
   {
      return pObject;
   }
}

/*
 * This function returns the module handle of our class-dll
 */
HMODULE QueryModuleHandle(string class_name)
{
   static HMODULE hmod=0;

   if(!hmod)
   {
      PSZ pathname=_somLocateClassFile(SOMClassMgrObject, somIdFromString(class_name),1,2);
      DosQueryModuleHandle(pathname,&hmod);  //Query module handle
   }
   return hmod;
}

/*
 * Dialog procedure for product info
 */
MRESULT EXPENTRY ProdInfoDlgProc( HWND hwnd, ULONG msg, MPARAM mp1,
                                  MPARAM mp2)
{
   switch(msg)
   {
      case WM_COMMAND:
         /*
          * No matter what the command, close the dialog
          */
         WinDismissDlg(hwnd, TRUE);
         break;

      default:
         return(WinDefDlgProc(hwnd, msg, mp1, mp2));
         break;
   }
   return (MRESULT)0;
}

/*
 * The prototype for ico_wpDragOver was replaced by the following prototype:
 */
SOM_Scope MRESULT  SOMLINK ico_wpDragOver(DDIcon *somSelf, HWND hwndCnr,
                                          PDRAGINFO pdrgInfo)
{
   ULONG  ulItemCnt   = 0;           // Number of items dragged over
   ULONG  ulItem      = 0;           // Item index
   USHORT usDropIndic = DOR_DROP;    // What to do with dragged items
   WPObject* object;
   BOOL success;

   /* DDIconData *somThis = DDIconGetData(somSelf);*/
   DDIconMethodDebug("DDIcon","ico_wpDragOver");

   _Pmpf(("Preforming 'wpDragOve'"));

   ulItemCnt = DrgQueryDragitemCount(pdrgInfo);

   /*
    * Check every dragged item. If one is not a WPS object, do not accept
    */
   for (ulItem=0; ulItem < ulItemCnt; ulItem++)
   {
      DRAGITEM DItem;

      success = DrgQueryDragitem(pdrgInfo, sizeof(DItem), &DItem, ulItem);
      if (!success)
      {
         usDropIndic=DOR_NEVERDROP;
         break;
      }

      object = GetOriginalObject(OBJECT_FROM_PREC((&DItem)->ulItemID));

      /*
       * Check if the item is a WPS object or an icon object. If it is not a WPS
       * object or if it is an icon object, do not accept the drop.
       */
      if(!DrgVerifyRMF(&DItem,"DRM_OBJECT","DRF_OBJECT") || _somIsA(object, _DDIcon))
      {
         usDropIndic=DOR_NEVERDROP;
         break;
      }
   }
return (MRFROM2SHORT (usDropIndic, DO_UNKNOWN));
}

/*
 * The prototype for ico_wpDrop was replaced by the following prototype:
 */
SOM_Scope MRESULT  SOMLINK ico_wpDrop(DDIcon *somSelf, HWND hwndCnr,
                                      PDRAGINFO pdrgInfo, PDRAGITEM pdrgItem)
{
   WPObject* object;
   WPObject* folderObject;
   BOOL success;
   CHAR   szObjectFilename[CCHMAXPATH];    // Buffer for wpQueryRealName()
   ULONG  cb  = sizeof(szObjectFilename);  // Size of object
   CHAR   szSetupString[12 + CCHMAXPATH];
   PSZ   pszSetupString= &szSetupString[0];
   USHORT rcDrop = RC_DROP_ERROR;

   /* DDIconData *somThis = DDIconGetData(somSelf); */
   DDIconMethodDebug("DDIcon","ico_wpDrop");

   _Pmpf(("Preforming 'wpDrop'"));

   object = GetOriginalObject(OBJECT_FROM_PREC(pdrgItem->ulItemID));

   success = _wpQueryRealName(somSelf, szObjectFilename, &cb, TRUE);

   /*
    * Assign a new icons to the dropped object using _wpSetup. If the object
    * is a folder and the "usOperation" is equal to "DO_COPY", then set the
    * animation icon.
    */
    if (success) {
            if (_somIsA(object, _WPFolder))
            {
               /*
                * A switch is used her since this portion of the code is going
                * to be expanded in order to change the default icon for the
                * wpFolder class.
                */
               switch (pdrgInfo->usOperation) {
               case DO_COPY:
                  strcpy(pszSetupString, "ICONNFILE=1,");
                  strcat(szSetupString, szObjectFilename);
                  success = _wpSetup(object, szSetupString);
                  _Pmpf(("DO_COPY _wpSetup returns : %d",success));
                  if (success) {
                     rcDrop = RC_DROP_ITEMCOMPLETE;
                  }
                       break;
               default:
                  strcpy(pszSetupString, "ICONFILE=");
                  strcat(szSetupString, szObjectFilename);
                  success = _wpSetup(object, szSetupString);
                  _Pmpf(("_wpSetup returns : %d",success));
                  if (success) {
                     rcDrop = RC_DROP_ITEMCOMPLETE;
                  }
                       break;
               }
            } else {
               strcpy(pszSetupString, "ICONFILE=");
               strcat(szSetupString, szObjectFilename);
               success = _wpSetup(object, szSetupString);
               _Pmpf(("_wpSetup returns : %d",success));
               if (success) {
                  rcDrop = RC_DROP_ITEMCOMPLETE;
               }
            }
    }
    return (MRFROMSHORT(rcDrop));
}


/*
 * The prototype for ico_wpModifyPopupMenu was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK ico_wpModifyPopupMenu(DDIcon *somSelf,
                                              HWND hwndMenu,
                                              HWND hwndCnr, ULONG iPosition)
{
   MENUITEM mi;

   /* DDIconData *somThis = DDIconGetData(somSelf); */
   DDIconMethodDebug("DDIcon","ico_wpModifyPopupMenu");

   _Pmpf(("Inserting 'Product info' menu"));

   /*
    * Get handle to the WPObject's "Help" submenu in the
    * the folder's popup menu
    */
   WinSendMsg(hwndMenu, MM_QUERYITEM, MPFROM2SHORT(WPMENUID_HELP, TRUE), (MPARAM)&mi);

   /*
    * mi.hwndSubMenu now contains "Help" submenu handle,
    * which we add items to now
    */
   winhInsertMenuSeparator(mi.hwndSubMenu, MIT_END, MENUID_SEPARATOR);
   winhInsertMenuItem(mi.hwndSubMenu, MIT_END, MENUID_PRODUCT_INFO, "DDIcon product info", MIS_TEXT, 0);

   return (DDIcon_parent_WPIcon_wpModifyPopupMenu(somSelf, hwndMenu, hwndCnr, iPosition));
}

/*
 * The prototype for ico_wpMenuItemSelected was replaced by the following prototype:
 */
SOM_Scope BOOL  SOMLINK ico_wpMenuItemSelected(DDIcon *somSelf,
                                               HWND hwndFrame,
                                               ULONG ulMenuId)
{
   PDLGTEMPLATE pdlgt;
   HMODULE    hmodResource;  // Resource module handle

   /* DDIconData *somThis = DDIconGetData(somSelf); */
   DDIconMethodDebug("DDIcon","ico_wpMenuItemSelected");

   if (ulMenuId == MENUID_PRODUCT_INFO)
   {
      _Pmpf(("Calling 'QueryModuleHandle'"));

      hmodResource = QueryModuleHandle("DDIcon");

      _Pmpf(("Calling 'WinCreateDlg'"));

      WinLoadDlg(HWND_DESKTOP, HWND_DESKTOP,
                 ProdInfoDlgProc,
                 hmodResource,
                 DLGID_PRODINFO,
                 NULL);
   }

   return (DDIcon_parent_WPIcon_wpMenuItemSelected(somSelf,
                                                   hwndFrame,
                                                   ulMenuId));
}
