
/*
 * This file was generated by the SOM Compiler.
 * FileName: DDIcon.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *  =====================================================================#
 *                                                                       #
 *    A replacement class for WPIcon, which makes it possible to change  #
 *    the icon of one or more objects, by dropping them on an icon       #
 *    object.                                                            #
 *    Copyright (C) 1999 Jens Borch Christiansen                         #
 *                                                                       #
 *    This program is free software; you can redistribute it and/or      #
 *    modify it under the terms of the GNU General Public License as     #
 *    published by the Free Software Foundation; either version 2 of     #
 *    the License, or (at your option) any later version.                #
 *                                                                       #
 *    This program is distributed in the hope that it will be useful,    #
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of     #
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      #
 *    GNU General Public License for more details.                       #
 *                                                                       #
 *    You should have received a copy of the GNU General Public License  #
 *    along with this program; if not, write to the Free Software        #
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA           #
 *    02111-1307  USA                                                    #
 *                                                                       #
 *  =====================================================================#
 *  =====================================================================#
 *                                                                       #
 *   CLASS: DDIcon                                                       #
 *                                                                       #
 *   CLASS HIERARCHY:                                                    #
 *                                                                       #
 *       SOMObject                                                       #
 *         ÀÄÄ WPObject                                                  #
 *               ÀÄÄ WPFileSystem                                        #
 *                     ÀÄÄ WPDataFile                                    #
 *                           ÀÄÄ WPIcon                                  #
 *                                 ÀÄÄ DDIcon                            #
 *                                                                       #
 *   DESCRIPTION:                                                        #
 *                                                                       #
 *   A replacement class for WPIcon, which makes it possible to change   #
 *   the icon of one or more objects, by dropping them on an icon        #
 *   object.                                                             #
 *                                                                       #
 *  =====================================================================#
 */


#ifndef SOM_DDIcon_h
#define SOM_DDIcon_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef DDIcon
#define DDIcon SOMObject
#endif
#include <wpicon.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_WPIcon
    #define M_WPIcon SOMObject
#endif /* M_WPIcon */
#ifndef M_DDIcon
    #define M_DDIcon SOMObject
#endif /* M_DDIcon */

/*
 * End of bindings for IDL types.
 */

#define DDIcon_MajorVersion 1
#define DDIcon_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define DDIconNewClass DDIconc
#pragma linkage(DDIconc, system)
#define DDIconClassData DDIcond
#define DDIconCClassData DDIconx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define DDIcon_classObj DDIconClassData.classObject
#define _DDIcon DDIcon_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK DDIconNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(DDIconNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct DDIconClassDataStructure {
	SOMClass *classObject;
} SOMDLINK DDIconClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct DDIconCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK DDIconCClassData;

/*
 * New and Renew macros for DDIcon
 */
#define DDIconNew() \
   ( _DDIcon ? \
	_somNew(_DDIcon) \
	: ( DDIconNewClass(\
		DDIcon_MajorVersion, \
		DDIcon_MinorVersion),\
	   _somNew(_DDIcon)))
#define DDIconRenew(buf) \
   ( _DDIcon ? \
	_somRenew(_DDIcon, buf) \
	: ( DDIconNewClass(\
		DDIcon_MajorVersion, \
		DDIcon_MinorVersion),\
	   _somRenew(_DDIcon, buf)))

/*
 * Override method: wpDragOver
 */
#define DDIcon_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define DDIcon_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpModifyPopupMenu
 */
#define DDIcon_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define DDIcon_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define DDIcon_wpQueryIcon WPObject_wpQueryIcon
#define DDIcon_wpSetupOnce WPObject_wpSetupOnce
#define DDIcon_wpFormatDragItem WPObject_wpFormatDragItem
#define DDIcon_wpQueryHandleFromContents WPDataFile_wpQueryHandleFromContents
#define DDIcon_wpSetContentsFromHandle WPDataFile_wpSetContentsFromHandle
#define DDIcon_somDefaultInit SOMObject_somDefaultInit
#define DDIcon_somDestruct SOMObject_somDestruct
#define DDIcon_wpAddBecomePage WPDataFile_wpAddBecomePage
#define DDIcon_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define DDIcon_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define DDIcon_wpPrintPifFile WPDataFile_wpPrintPifFile
#define DDIcon_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define DDIcon_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define DDIcon_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define DDIcon_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define DDIcon_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define DDIcon_wpSetContentsFromPointer WPDataFile_wpSetContentsFromPointer
#define DDIcon_wpQueryPointerFromContents WPDataFile_wpQueryPointerFromContents
#define DDIcon_wpRenderFromClipboard WPDataFile_wpRenderFromClipboard
#define DDIcon_wpRestoreState WPObject_wpRestoreState
#define DDIcon_wpSetDefaultView WPObject_wpSetDefaultView
#define DDIcon_wpSetRealName WPFileSystem_wpSetRealName
#define DDIcon_wpSetType WPFileSystem_wpSetType
#define DDIcon_wpAddSettingsPages WPObject_wpAddSettingsPages
#define DDIcon_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define DDIcon_wpOpen WPObject_wpOpen
#define DDIcon_wpPrintObject WPObject_wpPrintObject
#define DDIcon_wpModifyMenu WPObject_wpModifyMenu
#define DDIcon_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define DDIcon_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define DDIcon_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define DDIcon_wpRender WPObject_wpRender
#define DDIcon_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define DDIcon_wpQueryType WPFileSystem_wpQueryType
#define DDIcon_wpSetAttr WPFileSystem_wpSetAttr
#define DDIcon_wpQueryAttr WPFileSystem_wpQueryAttr
#define DDIcon_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define DDIcon_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define DDIcon_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define DDIcon_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define DDIcon_wpQueryCreation WPFileSystem_wpQueryCreation
#define DDIcon_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define DDIcon_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define DDIcon_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define DDIcon_wpQueryEASize WPFileSystem_wpQueryEASize
#define DDIcon_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define DDIcon_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define DDIcon_wpRefresh WPFileSystem_wpRefresh
#define DDIcon_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define DDIcon_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define DDIcon_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define DDIcon_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define DDIcon_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define DDIcon_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define DDIcon_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define DDIcon_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define DDIcon_wpQueryRealName WPFileSystem_wpQueryRealName
#define DDIcon_wpQueryFilename WPFileSystem_wpQueryFilename
#define DDIcon_wpQueryDisk WPFileSystem_wpQueryDisk
#define DDIcon_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define DDIcon_wpUnInitData WPObject_wpUnInitData
#define DDIcon_wpQueryHandle WPObject_wpQueryHandle
#define DDIcon_wpSaveImmediate WPObject_wpSaveImmediate
#define DDIcon_wpSetTitle WPObject_wpSetTitle
#define DDIcon_wpViewObject WPObject_wpViewObject
#define DDIcon_wpSwitchTo WPObject_wpSwitchTo
#define DDIcon_wpCopyObject WPObject_wpCopyObject
#define DDIcon_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define DDIcon_wpMoveObject WPObject_wpMoveObject
#define DDIcon_wpQueryIconData WPObject_wpQueryIconData
#define DDIcon_wpSetIconData WPObject_wpSetIconData
#define DDIcon_wpQueryDetailsData WPObject_wpQueryDetailsData
#define DDIcon_wpSaveState WPObject_wpSaveState
#define DDIcon_wpDraggedOverObject WPObject_wpDraggedOverObject
#define DDIcon_wpDroppedOnObject WPObject_wpDroppedOnObject
#define DDIcon_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define DDIcon_wpAppendObject WPObject_wpAppendObject
#define DDIcon_wpReplaceObject WPObject_wpReplaceObject
#define DDIcon_wpQueryStyle WPObject_wpQueryStyle
#define DDIcon_wpFilterMenu WPObject_wpFilterMenu
#define DDIcon_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define DDIcon_wpIdentify WPObject_wpIdentify
#define DDIcon_wpIsDeleteable WPObject_wpIsDeleteable
#define DDIcon_wpSetup WPObject_wpSetup
#define DDIcon_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define DDIcon_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define DDIcon_wpAddToObjUseList WPObject_wpAddToObjUseList
#define DDIcon_wpAllocMem WPObject_wpAllocMem
#define DDIcon_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define DDIcon_wpClose WPObject_wpClose
#define DDIcon_wpCnrInsertObject WPObject_wpCnrInsertObject
#define DDIcon_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define DDIcon_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define DDIcon_wpConfirmDelete WPObject_wpConfirmDelete
#define DDIcon_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define DDIcon_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define DDIcon_wpCreateAnother WPObject_wpCreateAnother
#define DDIcon_wpCreateShadowObject WPObject_wpCreateShadowObject
#define DDIcon_wpDelete WPObject_wpDelete
#define DDIcon_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define DDIcon_wpDisplayHelp WPObject_wpDisplayHelp
#define DDIcon_wpDisplayMenu WPObject_wpDisplayMenu
#define DDIcon_wpEndConversation WPObject_wpEndConversation
#define DDIcon_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define DDIcon_wpFindUseItem WPObject_wpFindUseItem
#define DDIcon_wpFree WPObject_wpFree
#define DDIcon_wpFreeMem WPObject_wpFreeMem
#define DDIcon_wpHide WPObject_wpHide
#define DDIcon_wpInitData WPObject_wpInitData
#define DDIcon_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define DDIcon_wpInsertMenuItems WPObject_wpInsertMenuItems
#define DDIcon_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define DDIcon_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define DDIcon_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define DDIcon_wpQueryConfirmations WPObject_wpQueryConfirmations
#define DDIcon_wpQueryDefaultView WPObject_wpQueryDefaultView
#define DDIcon_wpQueryError WPObject_wpQueryError
#define DDIcon_wpSetFolder WPObject_wpSetFolder
#define DDIcon_wpQueryFolder WPObject_wpQueryFolder
#define DDIcon_wpQueryMinWindow WPObject_wpQueryMinWindow
#define DDIcon_wpSetTaskRec WPObject_wpSetTaskRec
#define DDIcon_wpFindTaskRec WPObject_wpFindTaskRec
#define DDIcon_wpQueryTitle WPObject_wpQueryTitle
#define DDIcon_wpRegisterView WPObject_wpRegisterView
#define DDIcon_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define DDIcon_wpRenderComplete WPObject_wpRenderComplete
#define DDIcon_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define DDIcon_wpRestore WPObject_wpRestore
#define DDIcon_wpRestoreData WPObject_wpRestoreData
#define DDIcon_wpRestoreLong WPObject_wpRestoreLong
#define DDIcon_wpRestoreString WPObject_wpRestoreString
#define DDIcon_wpSaveData WPObject_wpSaveData
#define DDIcon_wpSaveDeferred WPObject_wpSaveDeferred
#define DDIcon_wpSaveLong WPObject_wpSaveLong
#define DDIcon_wpSaveString WPObject_wpSaveString
#define DDIcon_wpScanSetupString WPObject_wpScanSetupString
#define DDIcon_wpSetConcurrentView WPObject_wpSetConcurrentView
#define DDIcon_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define DDIcon_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define DDIcon_wpSetError WPObject_wpSetError
#define DDIcon_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define DDIcon_wpSetIcon WPObject_wpSetIcon
#define DDIcon_wpSetMinWindow WPObject_wpSetMinWindow
#define DDIcon_wpModifyStyle WPObject_wpModifyStyle
#define DDIcon_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define DDIcon_wpUnlockObject WPObject_wpUnlockObject
#define DDIcon_wpObjectReady WPObject_wpObjectReady
#define DDIcon_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define DDIcon_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define DDIcon_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define DDIcon_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define DDIcon_wpSetObjectID WPObject_wpSetObjectID
#define DDIcon_wpQueryObjectID WPObject_wpQueryObjectID
#define DDIcon_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define DDIcon_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define DDIcon_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define DDIcon_wpFindViewItem WPObject_wpFindViewItem
#define DDIcon_wpLockObject WPObject_wpLockObject
#define DDIcon_wpIsLocked WPObject_wpIsLocked
#define DDIcon_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define DDIcon_wpWaitForClose WPObject_wpWaitForClose
#define DDIcon_wpSetMenuStyle WPObject_wpSetMenuStyle
#define DDIcon_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define DDIcon_wpSetStyle WPObject_wpSetStyle
#define DDIcon_somInit SOMObject_somInit
#define DDIcon_somUninit SOMObject_somUninit
#define DDIcon_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define DDIcon_somDefaultAssign SOMObject_somDefaultAssign
#define DDIcon_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define DDIcon_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define DDIcon_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define DDIcon_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define DDIcon_somDefaultVAssign SOMObject_somDefaultVAssign
#define DDIcon_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define DDIcon_somFree SOMObject_somFree
#define DDIcon_somGetClass SOMObject_somGetClass
#define DDIcon_somGetClassName SOMObject_somGetClassName
#define DDIcon_somGetSize SOMObject_somGetSize
#define DDIcon_somIsA SOMObject_somIsA
#define DDIcon_somIsInstanceOf SOMObject_somIsInstanceOf
#define DDIcon_somRespondsTo SOMObject_somRespondsTo
#define DDIcon_somDispatch SOMObject_somDispatch
#define DDIcon_somClassDispatch SOMObject_somClassDispatch
#define DDIcon_somCastObj SOMObject_somCastObj
#define DDIcon_somResetObj SOMObject_somResetObj
#define DDIcon_somDispatchV SOMObject_somDispatchV
#define DDIcon_somDispatchL SOMObject_somDispatchL
#define DDIcon_somDispatchA SOMObject_somDispatchA
#define DDIcon_somDispatchD SOMObject_somDispatchD
#define DDIcon_somPrintSelf SOMObject_somPrintSelf
#define DDIcon_somDumpSelf SOMObject_somDumpSelf
#define DDIcon_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_DDIcon_h */

#ifndef SOM_M_DDIcon_h
#define SOM_M_DDIcon_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_DDIcon
#define M_DDIcon SOMObject
#endif
#include <wpicon.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_DDIcon_MajorVersion 1
#define M_DDIcon_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_DDIconNewClass DDIconc
#pragma linkage(DDIconc, system)
#define M_DDIconClassData DDIcond
#define M_DDIconCClassData DDIconx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_DDIcon_classObj M_DDIconClassData.classObject
#define _M_DDIcon M_DDIcon_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_DDIconNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_DDIconNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_DDIconClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_DDIconClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_DDIconCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_DDIconCClassData;

/*
 * New and Renew macros for M_DDIcon
 */
#define M_DDIconNew() \
   ( _M_DDIcon ? \
	_somNew(_M_DDIcon) \
	: ( M_DDIconNewClass(\
		M_DDIcon_MajorVersion, \
		M_DDIcon_MinorVersion),\
	   _somNew(_M_DDIcon)))
#define M_DDIconRenew(buf) \
   ( _M_DDIcon ? \
	_somRenew(_M_DDIcon, buf) \
	: ( M_DDIconNewClass(\
		M_DDIcon_MajorVersion, \
		M_DDIcon_MinorVersion),\
	   _somRenew(_M_DDIcon, buf)))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_DDIcon_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_DDIcon_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_DDIcon_wpclsInitData M_WPObject_wpclsInitData
#define M_DDIcon_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_DDIcon_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_DDIcon_wpclsAddClipboardAssoc M_WPDataFile_wpclsAddClipboardAssoc
#define M_DDIcon_wpclsEnumClipboardClasses M_WPDataFile_wpclsEnumClipboardClasses
#define M_DDIcon_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_DDIcon_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_DDIcon_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_DDIcon_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_DDIcon_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_DDIcon_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_DDIcon_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_DDIcon_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_DDIcon_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_DDIcon_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_DDIcon_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_DDIcon_wpclsNew M_WPObject_wpclsNew
#define M_DDIcon_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_DDIcon_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_DDIcon_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_DDIcon_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_DDIcon_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_DDIcon_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_DDIcon_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_DDIcon_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_DDIcon_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_DDIcon_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_DDIcon_wpclsSetError M_WPObject_wpclsSetError
#define M_DDIcon_wpclsQueryError M_WPObject_wpclsQueryError
#define M_DDIcon_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_DDIcon_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_DDIcon_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_DDIcon_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_DDIcon_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_DDIcon_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_DDIcon_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_DDIcon_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_DDIcon_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_DDIcon_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_DDIcon_somUninit SOMObject_somUninit
#define M_DDIcon_somClassReady SOMClass_somClassReady
#define M_DDIcon_somNew SOMClass_somNew
#define M_DDIcon_somRenew SOMClass_somRenew
#define M_DDIcon__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_DDIcon__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_DDIcon__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_DDIcon_somNewNoInit SOMClass_somNewNoInit
#define M_DDIcon_somRenewNoInit SOMClass_somRenewNoInit
#define M_DDIcon_somRenewNoZero SOMClass_somRenewNoZero
#define M_DDIcon_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_DDIcon_somAllocate SOMClass_somAllocate
#define M_DDIcon_somDeallocate SOMClass_somDeallocate
#define M_DDIcon_somInitClass SOMClass_somInitClass
#define M_DDIcon_somInitMIClass SOMClass_somInitMIClass
#define M_DDIcon_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_DDIcon_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_DDIcon_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_DDIcon_somGetApplyStub SOMClass_somGetApplyStub
#define M_DDIcon_somGetClassData SOMClass_somGetClassData
#define M_DDIcon_somSetClassData SOMClass_somSetClassData
#define M_DDIcon_somGetClassMtab SOMClass_somGetClassMtab
#define M_DDIcon_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_DDIcon_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_DDIcon_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_DDIcon_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_DDIcon_somGetMemberToken SOMClass_somGetMemberToken
#define M_DDIcon_somGetMethodData SOMClass_somGetMethodData
#define M_DDIcon_somGetRdStub SOMClass_somGetRdStub
#define M_DDIcon_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_DDIcon_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_DDIcon_somGetMethodToken SOMClass_somGetMethodToken
#define M_DDIcon_somGetName SOMClass_somGetName
#define M_DDIcon_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_DDIcon_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_DDIcon_somGetNumMethods SOMClass_somGetNumMethods
#define M_DDIcon_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_DDIcon_somGetParent SOMClass_somGetParent
#define M_DDIcon_somGetParents SOMClass_somGetParents
#define M_DDIcon_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_DDIcon_somFindMethod SOMClass_somFindMethod
#define M_DDIcon_somFindMethodOk SOMClass_somFindMethodOk
#define M_DDIcon_somFindSMethod SOMClass_somFindSMethod
#define M_DDIcon_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_DDIcon_somLookupMethod SOMClass_somLookupMethod
#define M_DDIcon_somCheckVersion SOMClass_somCheckVersion
#define M_DDIcon_somDescendedFrom SOMClass_somDescendedFrom
#define M_DDIcon_somSupportsMethod SOMClass_somSupportsMethod
#define M_DDIcon_somDefinedMethod SOMClass_somDefinedMethod
#define M_DDIcon_somOverrideMtab SOMClass_somOverrideMtab
#define M_DDIcon_somDefaultInit SOMObject_somDefaultInit
#define M_DDIcon_somDestruct SOMObject_somDestruct
#define M_DDIcon_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_DDIcon_somDefaultAssign SOMObject_somDefaultAssign
#define M_DDIcon_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_DDIcon_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_DDIcon_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_DDIcon_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_DDIcon_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_DDIcon_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_DDIcon_somInit SOMObject_somInit
#define M_DDIcon_somFree SOMObject_somFree
#define M_DDIcon_somGetClass SOMObject_somGetClass
#define M_DDIcon_somGetClassName SOMObject_somGetClassName
#define M_DDIcon_somGetSize SOMObject_somGetSize
#define M_DDIcon_somIsA SOMObject_somIsA
#define M_DDIcon_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_DDIcon_somRespondsTo SOMObject_somRespondsTo
#define M_DDIcon_somDispatch SOMObject_somDispatch
#define M_DDIcon_somClassDispatch SOMObject_somClassDispatch
#define M_DDIcon_somCastObj SOMObject_somCastObj
#define M_DDIcon_somResetObj SOMObject_somResetObj
#define M_DDIcon_somDispatchV SOMObject_somDispatchV
#define M_DDIcon_somDispatchL SOMObject_somDispatchL
#define M_DDIcon_somDispatchA SOMObject_somDispatchA
#define M_DDIcon_somDispatchD SOMObject_somDispatchD
#define M_DDIcon_somPrintSelf SOMObject_somPrintSelf
#define M_DDIcon_somDumpSelf SOMObject_somDumpSelf
#define M_DDIcon_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_DDIcon_h */
